/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrames;

import Database.DBConnector;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Selitha Sasmitha
 */
public class Dresses extends javax.swing.JFrame {

    /**
     * Creates new form Dresses
     */
    public Dresses() {
        initComponents();
        update_table();   //Calling the Update table function
        autoGenItemNum();//Function call for autogenerate the Dress ID
        
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        btnMinimize = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtDressCode = new app.bolivia.swing.JCTextField();
        jLabel1 = new javax.swing.JLabel();
        txtDressName = new app.bolivia.swing.JCTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbCategory = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cmbSize = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtColor = new app.bolivia.swing.JCTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPrice = new app.bolivia.swing.JCTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPath = new app.bolivia.swing.JCTextField();
        btnUploadImage = new rojerusan.RSMaterialButtonRectangle();
        btnAddDress = new rojerusan.RSMaterialButtonRectangle();
        jLabel8 = new javax.swing.JLabel();
        txtQuantity = new app.bolivia.swing.JCTextField();
        jPanel2 = new javax.swing.JPanel();
        txtDressSearch = new app.bolivia.swing.JCTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableDress = new rojeru_san.complementos.RSTableMetro();
        btnDeleteDress = new rojerusan.RSMaterialButtonRectangle();
        btnUpdateDress = new rojerusan.RSMaterialButtonRectangle();
        lblImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(84, 109, 229));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons used in this project/icons/Back.png"))); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        btnMinimize.setBackground(new java.awt.Color(84, 109, 229));
        btnMinimize.setForeground(new java.awt.Color(255, 255, 255));
        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons used in this project/icons/Minimize Set 27px.png"))); // NOI18N
        btnMinimize.setAlignmentY(0.0F);
        btnMinimize.setBorder(null);
        btnMinimize.setBorderPainted(false);
        btnMinimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizeActionPerformed(evt);
            }
        });
        jPanel1.add(btnMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 0, 30, 30));

        btnClose.setBackground(new java.awt.Color(84, 109, 229));
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons used in this project/icons/Close Set 27 px.png"))); // NOI18N
        btnClose.setAlignmentY(0.0F);
        btnClose.setBorder(null);
        btnClose.setBorderPainted(false);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 0, 30, 30));

        jLabel9.setFont(new java.awt.Font("Slicker", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Manage Dresses");
        jLabel9.setToolTipText("");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 250, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 50));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDressCode.setEditable(false);
        txtDressCode.setBackground(new java.awt.Color(51, 51, 51));
        txtDressCode.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtDressCode.setForeground(new java.awt.Color(255, 255, 255));
        txtDressCode.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtDressCode.setPhColor(new java.awt.Color(255, 255, 255));
        txtDressCode.setPlaceholder("Enter Dress code");
        jPanel3.add(txtDressCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 260, 30));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Dress Code  :");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));
        jLabel1.getAccessibleContext().setAccessibleName("Dress code :");

        txtDressName.setBackground(new java.awt.Color(51, 51, 51));
        txtDressName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtDressName.setForeground(new java.awt.Color(255, 255, 255));
        txtDressName.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtDressName.setPhColor(new java.awt.Color(255, 255, 255));
        txtDressName.setPlaceholder("Enter item name ...");
        jPanel3.add(txtDressName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 260, 30));

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name :");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Categery :");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        cmbCategory.setBackground(new java.awt.Color(51, 51, 51));
        cmbCategory.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmbCategory.setForeground(new java.awt.Color(255, 255, 255));
        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " Men's Shirts", " Men's Jackets", " Men's Trousers", " Men's Shoes", " Men's Ties", " Women's Saree", " Women's Frocks", " Women's Shoes" }));
        cmbCategory.setBorder(null);
        jPanel3.add(cmbCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 260, 30));

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Size :");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        cmbSize.setBackground(new java.awt.Color(51, 51, 51));
        cmbSize.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmbSize.setForeground(new java.awt.Color(255, 255, 255));
        cmbSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " Small", " Medium", " Large", " XL", " XXL", " XXL", " 28\" - 32\"  inch", " 32\" - 36\"  inch", " 36\" - 42\"  inch", " 6 -  8 US Size", " 8 -  9 US Size", " 9 - 12 US Size", " " }));
        cmbSize.setBorder(null);
        jPanel3.add(cmbSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 260, 30));

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Colour :");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        txtColor.setBackground(new java.awt.Color(51, 51, 51));
        txtColor.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtColor.setForeground(new java.awt.Color(255, 255, 255));
        txtColor.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtColor.setPhColor(new java.awt.Color(255, 255, 255));
        txtColor.setPlaceholder("Enter colour ...");
        jPanel3.add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 260, 30));

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Price (Per Day) :");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, -1));

        txtPrice.setBackground(new java.awt.Color(51, 51, 51));
        txtPrice.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtPrice.setForeground(new java.awt.Color(255, 255, 255));
        txtPrice.setText("0");
        txtPrice.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtPrice.setPhColor(new java.awt.Color(255, 255, 255));
        txtPrice.setPlaceholder("Enter rent price ...");
        txtPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPriceKeyTyped(evt);
            }
        });
        jPanel3.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 260, 30));

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Image :");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, -1, -1));

        txtPath.setBackground(new java.awt.Color(51, 51, 51));
        txtPath.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtPath.setForeground(new java.awt.Color(255, 255, 255));
        txtPath.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtPath.setPhColor(new java.awt.Color(255, 255, 255));
        txtPath.setPlaceholder("Upload an image ..");
        jPanel3.add(txtPath, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 120, 30));

        btnUploadImage.setBackground(new java.awt.Color(153, 153, 153));
        btnUploadImage.setText("Upload");
        btnUploadImage.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        btnUploadImage.setName(""); // NOI18N
        btnUploadImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadImageActionPerformed(evt);
            }
        });
        jPanel3.add(btnUploadImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 560, 130, 50));

        btnAddDress.setText("ADD");
        btnAddDress.setFont(new java.awt.Font("Slicker", 0, 24)); // NOI18N
        btnAddDress.setName(""); // NOI18N
        btnAddDress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDressActionPerformed(evt);
            }
        });
        jPanel3.add(btnAddDress, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 640, 280, 70));

        jLabel8.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Quantity :");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        txtQuantity.setBackground(new java.awt.Color(51, 51, 51));
        txtQuantity.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtQuantity.setForeground(new java.awt.Color(255, 255, 255));
        txtQuantity.setText("0");
        txtQuantity.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtQuantity.setPhColor(new java.awt.Color(255, 255, 255));
        txtQuantity.setPlaceholder("Enter Quanity ...");
        txtQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQuantityKeyTyped(evt);
            }
        });
        jPanel3.add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 260, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 300, 730));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDressSearch.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 2, true));
        txtDressSearch.setPlaceholder("Enter item name ...");
        txtDressSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDressSearchKeyReleased(evt);
            }
        });
        jPanel2.add(txtDressSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1030, -1));

        jtableDress.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dress Code", "Dress Name", "Category", "Size", "Quantity", "Colour", "Price(perday)", "Image"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtableDress.setFuenteFilas(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtableDress.setFuenteHead(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jtableDress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableDressMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtableDress);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 1030, 330));

        btnDeleteDress.setBackground(new java.awt.Color(51, 51, 51));
        btnDeleteDress.setText("Delete");
        btnDeleteDress.setFont(new java.awt.Font("Slicker", 0, 24)); // NOI18N
        btnDeleteDress.setName(""); // NOI18N
        btnDeleteDress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteDressActionPerformed(evt);
            }
        });
        jPanel2.add(btnDeleteDress, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 550, 190, -1));

        btnUpdateDress.setBackground(new java.awt.Color(51, 51, 51));
        btnUpdateDress.setText("Update");
        btnUpdateDress.setFont(new java.awt.Font("Slicker", 0, 24)); // NOI18N
        btnUpdateDress.setName(""); // NOI18N
        btnUpdateDress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateDressActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdateDress, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 550, 190, -1));

        lblImage.setBackground(new java.awt.Color(153, 153, 153));
        lblImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 260, 270));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 1070, 730));

        setSize(new java.awt.Dimension(1363, 764));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteDressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteDressActionPerformed
        // Delete Button codes
        
        DefaultTableModel d1 = (DefaultTableModel)jtableDress.getModel();

        int selectIndex = jtableDress.getSelectedRow();

        String Did = d1.getValueAt(selectIndex,0).toString();

        int  dialogResult = JOptionPane.showConfirmDialog(this,"Aye you Sure to Delete The Dress?","Warning",JOptionPane.YES_NO_OPTION);

        if(dialogResult == JOptionPane.YES_OPTION)
        {
            try {

                DBConnector dbCon = new DBConnector();
                Connection con = dbCon.getConnection();

                PreparedStatement pst = null;
                pst = con.prepareStatement("DELETE FROM `dress` WHERE `dress_code`=?");

                pst.setString(1,Did);
                pst.executeUpdate();

                JOptionPane.showMessageDialog(this, "Dress Details Deleted");
                update_table();

            } catch (SQLException ex) {
                Logger.getLogger(Customers.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        
        
    }//GEN-LAST:event_btnDeleteDressActionPerformed

    private void btnUpdateDressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateDressActionPerformed
        // Dress Update button codes
        
        DefaultTableModel d1 = (DefaultTableModel)jtableDress.getModel();
        
        int selectIndex = jtableDress.getSelectedRow();

        try {

            String Dressid = d1.getValueAt(selectIndex,0).toString();
            String Dname = txtDressName.getText();
            String Dcategory = cmbCategory.getSelectedItem().toString();
            String Dsize = cmbSize.getSelectedItem().toString();
            int Dqty = Integer.parseInt(txtQuantity.getText());
            String Dcolor = txtColor.getText();
            int  Dprice = Integer.parseInt(txtPrice.getText());
           

            DBConnector dbCon = new DBConnector();
            Connection con = dbCon.getConnection();

            PreparedStatement pst = null;
            pst = con.prepareStatement("UPDATE `dress` SET `dress_name`=?,`category`=?,`size`=?,`quantity`=?,`colour`=?,`price`=? WHERE `dress_code`=?");

            pst.setString(1,Dname);
            pst.setString(2,Dcategory);
            pst.setString(3,Dsize);
            pst.setInt(4,Dqty);
            pst.setString(5,Dcolor);
            pst.setInt(6,Dprice);
            pst.setString(7,Dressid);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Dress Details Updated");
            update_table();

        } catch (SQLException ex) {
            Logger.getLogger(Customers.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnUpdateDressActionPerformed

    private void btnAddDressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDressActionPerformed
        // Add dress button codes

        String Dcode = txtDressCode.getText();
        String Dname = txtDressName.getText();
        String Dcategory = cmbCategory.getSelectedItem().toString();
        String Dsize = cmbSize.getSelectedItem().toString();
        Integer Dqty = Integer.parseInt(txtQuantity.getText());
        String Dcolor = txtColor.getText();
        Integer  Dprice = Integer.parseInt(txtPrice.getText());
        
        /* *********************************************************/
        /*            Validation for the empty fields             **/ 
        /* *********************************************************/ 

        if(Dname.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Insert Dress name");
        }
        else if(Dqty.equals(0))
        {
            JOptionPane.showMessageDialog(null, "Enter Dress Quantity");
        }

        else if(Dcolor.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Insert Dress color");
        }

        else if(Dprice.equals(0))
        {
            JOptionPane.showMessageDialog(null, "Insert a Price");
        }
        
        else if(checkDressCode(Dcode))
        {
            JOptionPane.showMessageDialog(null," Dress is Already Exist for this Code"); // check exiasting emails
        }

      
        else {

            try {
                DBConnector dbCon = new DBConnector();
                Connection con = dbCon.getConnection();

                PreparedStatement pst = null;
                pst = con.prepareStatement("INSERT INTO `dress`(`dress_code`, `dress_name`, `category`, `size`,`quantity`, `colour`, `price`, `image`) VALUES (?,?,?,?,?,?,?,?)");

                pst.setString(1,Dcode);
                pst.setString(2, Dname);
                pst.setString(3, Dcategory);
                pst.setString(4, Dsize);
                pst.setInt(5, Dqty);
                pst.setString(6, Dcolor);
                pst.setInt(7, Dprice);
                pst.setBytes(8, photo);
                pst.executeUpdate();

                JOptionPane.showMessageDialog(this,"New Dress Added");
                
         /* *********************************************************/
        /*   Clearing the text fields after adding a new record    */ 
        /* *********************************************************/

                txtDressName.setText("");
                cmbCategory.setSelectedIndex(-1);
                cmbSize.setSelectedIndex(-1);
                txtColor.setText("");
                txtPrice.setText("");
                txtQuantity.setText("");
                txtDressName.requestFocus();
                
                autoGenItemNum(); //function call for Auto number
                update_table(); //Function call for Update the table

            }
            catch (SQLException ex) {
                Logger.getLogger(Dresses.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_btnAddDressActionPerformed

        byte[] photo =null;
        String filename =null;
        private ImageIcon format=null;
    
    private void btnUploadImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadImageActionPerformed
        // Upload image button codes
        
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        lblImage.setIcon(new ImageIcon(f.toString()));
        filename = f.getAbsolutePath();
        txtPath.setText(filename);
        
        try {
            File image = new File(filename);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf=new byte [1204];
                for(int readNum; (readNum=fis.read(buf))!=-1;)
                {
                    bos.write(buf, 0 ,readNum);
                }
                photo=bos.toByteArray();
                                       
        }
            
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        
    }//GEN-LAST:event_btnUploadImageActionPerformed

    private void jtableDressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableDressMouseClicked
        // Update text fields when select the record in the table
        
        DefaultTableModel d1 = (DefaultTableModel)jtableDress.getModel();

        int selectIndex = jtableDress.getSelectedRow();

        txtDressCode.setText(d1.getValueAt(selectIndex, 0).toString());
        txtDressName.setText(d1.getValueAt(selectIndex, 1).toString());
        cmbCategory.setSelectedItem(d1.getValueAt(selectIndex, 2).toString());
        cmbSize.setSelectedItem(d1.getValueAt(selectIndex, 3).toString());
        txtQuantity.setText(d1.getValueAt(selectIndex, 4).toString());
        txtColor.setText(d1.getValueAt(selectIndex, 5).toString());
        txtPrice.setText(d1.getValueAt(selectIndex, 6).toString());
        
        //ImageIcon imgicon = (ImageIcon) jtableDress.getValueAt(selectIndex, 6);
        //mage imgicon2 = imgicon.getImage().getScaledInstance(lblImage.getWidth(), lblImage.getHeight(),Image.SCALE_SMOOTH);
        //ImageIcon imgicon3 = new ImageIcon(imgicon2);
             
        //lblImage.setIcon(imgicon3);
        
   
       
        
    }//GEN-LAST:event_jtableDressMouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        
        ManagerMainMenu menu = new ManagerMainMenu();
        menu.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jLabel15MouseClicked

    private void txtDressSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDressSearchKeyReleased
        // Search filter for search bar when key typed
        
        DefaultTableModel d1 = (DefaultTableModel)jtableDress.getModel();
        String search = txtDressSearch.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(d1);
        jtableDress.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_txtDressSearchKeyReleased

    private void txtQuantityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantityKeyTyped
        /* *********************************************************/
        /*     Function not to put charactors into text  field     */ 
        /* *********************************************************/    
        
       char c = evt.getKeyChar();
       if(!Character.isDigit(c))
        {
            evt.consume();
           // JOptionPane.showMessageDialog(null, "Insert a Quantity");
        }
                
    }//GEN-LAST:event_txtQuantityKeyTyped

    private void txtPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriceKeyTyped
         /* *********************************************************/
        /*    Function not to put charactors into text  field       */ 
        /* *********************************************************/       
        char c2 = evt.getKeyChar();
        if(!Character.isDigit(c2))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtPriceKeyTyped

    private void btnMinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizeActionPerformed
        // Minimize Button
        this.setExtendedState(ManagerMainMenu.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // Close Button
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    
         /* *********************************************************/
         /*      Function to auto generate the dress number        */ 
        /* *********************************************************/ 
    
    public void autoGenItemNum() //Function for autogenerate the Dress ID
                    
    {       
        try {
            DBConnector dbCon = new DBConnector();
            Connection con = dbCon.getConnection();
              
            Statement stmt = con.createStatement();   
            
            ResultSet rs = stmt.executeQuery("Select Max(dress_code)from dress");
            rs.next();
            rs.getString( "Max(dress_code)");
            
            if(rs.getString( "Max(dress_code)") == null)
            {
                txtDressCode.setText("D001");
            }
            else
            {
                long id = Long.parseLong(rs.getString( "Max(dress_code)").substring(2,rs.getString("Max(dress_code)").length()));
                id++;
                
                txtDressCode.setText("D" + String.format("%03d",id));
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Dresses.class.getName()).log(Level.SEVERE, null, ex);
        }
          
    }
    
    
         /* *********************************************************/
        /* *****************Function Update table data******/ 
        /* *********************************************************/   
    
    
    public void update_table()
    {
        int c;
        
         try {
            DBConnector dbCon = new DBConnector();
            Connection con = dbCon.getConnection();
           
            PreparedStatement pst = null;
            pst = con.prepareStatement("SELECT * FROM `dress`");
            ResultSet Rs  = pst.executeQuery();
            
            ResultSetMetaData rd = Rs.getMetaData();
            c = rd.getColumnCount();
            DefaultTableModel df = (DefaultTableModel)jtableDress.getModel();
            df.setRowCount(0);
            
            while(Rs.next())
            {
                Vector v2 = new Vector();
                for (int i=1; i<=c; i++)
                {
                   v2.add(Rs.getString("dress_code"));
                   v2.add(Rs.getString("dress_name"));
                   v2.add(Rs.getString("category"));
                   v2.add(Rs.getString("size"));
                   v2.add(Rs.getInt("quantity"));
                   v2.add(Rs.getString("colour"));
                   v2.add(Rs.getInt("price"));
                   v2.add(Rs.getBytes("image"));
                }
                
                df.addRow(v2);
                
            }
          
            
        } catch (SQLException ex) {
            Logger.getLogger(Dresses.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
        /* *********************************************************/
        /* Function check the Dress code already exists***************/ 
        /* *********************************************************/ 
    
    public boolean checkDressCode(String DCodecheck) //Function to avoid Duplicate entry of Dress ID
    {
       PreparedStatement st;
       ResultSet rs;
       boolean check_DressCode = false;
       String query = "SELECT * FROM `dress` WHERE `dress_code` =?";
       
        try 
        {
            st = DBConnector.getConnection().prepareStatement(query);
            st.setString(1,DCodecheck);
            
            rs = st.executeQuery();
            
            if(rs.next())
            {
                check_DressCode = true;
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Dresses.class.getName()).log(Level.SEVERE, null, ex);
        }
      
        return check_DressCode;
       
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dresses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dresses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dresses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dresses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dresses().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle btnAddDress;
    private javax.swing.JButton btnClose;
    private rojerusan.RSMaterialButtonRectangle btnDeleteDress;
    private javax.swing.JButton btnMinimize;
    private rojerusan.RSMaterialButtonRectangle btnUpdateDress;
    private rojerusan.RSMaterialButtonRectangle btnUploadImage;
    private javax.swing.JComboBox<String> cmbCategory;
    private javax.swing.JComboBox<String> cmbSize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private rojeru_san.complementos.RSTableMetro jtableDress;
    private javax.swing.JLabel lblImage;
    private app.bolivia.swing.JCTextField txtColor;
    private app.bolivia.swing.JCTextField txtDressCode;
    private app.bolivia.swing.JCTextField txtDressName;
    private app.bolivia.swing.JCTextField txtDressSearch;
    private app.bolivia.swing.JCTextField txtPath;
    private app.bolivia.swing.JCTextField txtPrice;
    private app.bolivia.swing.JCTextField txtQuantity;
    // End of variables declaration//GEN-END:variables



}
