/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrames;


import Database.DBConnector;
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author Selitha Sasmitha
 */
public class ManagerMainMenu extends javax.swing.JFrame {

    /**
     * Creates new form ManagerMainMenu
     *
     */
    
    //color code variables to make hover effects
    
    Color mouseEnteredcolor = new Color (255,63,52);
    Color mouseExitdcolor = new Color (51,51,51);
    Color LogoutmouseEnteredcolor = new Color (84,109,229);
    
    
    public ManagerMainMenu() {
        initComponents();
        setDataToCard();
       
               
        /*code to hide the unwanted access from operetor*/
        /*when click back button, welcome lable and user account email will display*/
        
        String urole = Login.userRole;
        String Username = Login.Uemail;
      
  
        if(Login.userRole.equals("Manager")) 
        {
            
            lblwelcome.setText( urole );
            lbluser.setText(Username);
        }
        
        else if (Login.userRole.equals("Operator"))
        {
            
            lblwelcome.setText( urole );
            lbluser.setText(Username);
            
            lblUsers.setVisible(false);
            lblReports.setVisible(false);
            
            
        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnMinimize = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        lblwelcome = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblLogout = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lblDresses = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lblRent = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lblReturn = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        lblPayment = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        lblUsers = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        lblCustomers = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        lblReports = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        noOfItems = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        noOfCus = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        noOfUsers = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        noOfSales = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        onGoingRentals = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        pendingPayments = new javax.swing.JLabel();
        lbluser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(84, 109, 229));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons used in this project/icons/icons8_menu_48px_1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 30, 40));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setAlignmentX(0.0F);
        jPanel2.setAlignmentY(0.0F);
        jPanel2.setLayout(null);
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 7, 4, 38));

        jLabel2.setFont(new java.awt.Font("Waltograph UI", 0, 34)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Seasonal Dresser");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, 40));

        jLabel3.setFont(new java.awt.Font("Slicker", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Rental Management System");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Simplified Arabic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons used in this project/icons/male user 40px.png"))); // NOI18N
        jLabel4.setText("Welcome,");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 10, -1, -1));

        btnMinimize.setBackground(new java.awt.Color(84, 109, 229));
        btnMinimize.setForeground(new java.awt.Color(255, 255, 255));
        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons used in this project/icons/Minimize Set 27px.png"))); // NOI18N
        btnMinimize.setAlignmentY(0.0F);
        btnMinimize.setBorder(null);
        btnMinimize.setBorderPainted(false);
        btnMinimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizeActionPerformed(evt);
            }
        });
        jPanel1.add(btnMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 0, 30, 30));

        btnClose.setBackground(new java.awt.Color(84, 109, 229));
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons used in this project/icons/Close Set 27 px.png"))); // NOI18N
        btnClose.setAlignmentY(0.0F);
        btnClose.setBorder(null);
        btnClose.setBorderPainted(false);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 0, 30, 30));

        lblwelcome.setFont(new java.awt.Font("Simplified Arabic", 0, 16)); // NOI18N
        lblwelcome.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(lblwelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 20, 80, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 50));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 63, 52));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Slicker", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons used in this project/icons/icons8_Home_26px_2.png"))); // NOI18N
        jLabel6.setText("    Home Page");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 12, -1, -1));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 210, 50));

        jLabel5.setFont(new java.awt.Font("Simplified Arabic Fixed", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Features");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogout.setFont(new java.awt.Font("Slicker", 0, 18)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(255, 255, 255));
        lblLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons used in this project/icons/Logout.png"))); // NOI18N
        lblLogout.setText("    Logout");
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLogoutMouseExited(evt);
            }
        });
        jPanel5.add(lblLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 5, 220, -1));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 210, 50));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDresses.setFont(new java.awt.Font("Slicker", 0, 18)); // NOI18N
        lblDresses.setForeground(new java.awt.Color(255, 255, 255));
        lblDresses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons used in this project/icons/Dresses 26 px.png"))); // NOI18N
        lblDresses.setText("    Dresses");
        lblDresses.setAlignmentX(0.5F);
        lblDresses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDressesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDressesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDressesMouseExited(evt);
            }
        });
        jPanel6.add(lblDresses, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 210, -1));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 210, 50));

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRent.setFont(new java.awt.Font("Slicker", 0, 18)); // NOI18N
        lblRent.setForeground(new java.awt.Color(255, 255, 255));
        lblRent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons used in this project/icons/Rent Dresses 2.png"))); // NOI18N
        lblRent.setText("    Rent");
        lblRent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRentMouseExited(evt);
            }
        });
        jPanel7.add(lblRent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 210, -1));

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 210, 50));

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblReturn.setFont(new java.awt.Font("Slicker", 0, 18)); // NOI18N
        lblReturn.setForeground(new java.awt.Color(255, 255, 255));
        lblReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons used in this project/icons/Return Dresses 2.png"))); // NOI18N
        lblReturn.setText("    Return");
        lblReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReturnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblReturnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblReturnMouseExited(evt);
            }
        });
        jPanel8.add(lblReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 5, 210, -1));

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 210, 50));

        jPanel9.setBackground(new java.awt.Color(51, 51, 51));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPayment.setFont(new java.awt.Font("Slicker", 0, 18)); // NOI18N
        lblPayment.setForeground(new java.awt.Color(255, 255, 255));
        lblPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons used in this project/icons/Payments.png"))); // NOI18N
        lblPayment.setText("    Payment");
        lblPayment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPaymentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPaymentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPaymentMouseExited(evt);
            }
        });
        jPanel9.add(lblPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 5, 210, -1));

        jPanel3.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 210, 50));

        jPanel10.setBackground(new java.awt.Color(51, 51, 51));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsers.setFont(new java.awt.Font("Slicker", 0, 18)); // NOI18N
        lblUsers.setForeground(new java.awt.Color(255, 255, 255));
        lblUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons used in this project/icons/Users.png"))); // NOI18N
        lblUsers.setText("    Users");
        lblUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUsersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUsersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUsersMouseExited(evt);
            }
        });
        jPanel10.add(lblUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, -1));

        jPanel3.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 210, 50));

        jPanel11.setBackground(new java.awt.Color(51, 51, 51));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCustomers.setFont(new java.awt.Font("Slicker", 0, 18)); // NOI18N
        lblCustomers.setForeground(new java.awt.Color(255, 255, 255));
        lblCustomers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons used in this project/icons/Customers.png"))); // NOI18N
        lblCustomers.setText("    Customers");
        lblCustomers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCustomersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCustomersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCustomersMouseExited(evt);
            }
        });
        jPanel11.add(lblCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 200, -1));

        jPanel3.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 210, 50));

        jPanel12.setBackground(new java.awt.Color(51, 51, 51));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblReports.setFont(new java.awt.Font("Slicker", 0, 18)); // NOI18N
        lblReports.setForeground(new java.awt.Color(255, 255, 255));
        lblReports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons used in this project/icons/Reports.png"))); // NOI18N
        lblReports.setText("    Reports");
        lblReports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReportsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblReportsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblReportsMouseExited(evt);
            }
        });
        jPanel12.add(lblReports, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 200, -1));

        jPanel3.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 210, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 210, 730));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setForeground(new java.awt.Color(255, 255, 255));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setBackground(new java.awt.Color(164, 166, 164));
        jPanel14.setBorder(javax.swing.BorderFactory.createMatteBorder(20, 0, 0, 0, new java.awt.Color(255, 63, 52)));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        noOfItems.setFont(new java.awt.Font("Slicker", 1, 60)); // NOI18N
        noOfItems.setForeground(new java.awt.Color(71, 71, 71));
        noOfItems.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noOfItems.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons used in this project/icons/bgimg noofitems.png"))); // NOI18N
        noOfItems.setText("10");
        jPanel14.add(noOfItems, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 250, 130));

        jPanel13.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 250, 200));

        jLabel9.setFont(new java.awt.Font("Slicker", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(71, 71, 71));
        jLabel9.setText("No of Items");
        jPanel13.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        jLabel10.setFont(new java.awt.Font("Slicker", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(71, 71, 71));
        jLabel10.setText("No of Customers");
        jPanel13.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, -1, -1));

        jPanel15.setBackground(new java.awt.Color(164, 166, 164));
        jPanel15.setBorder(javax.swing.BorderFactory.createMatteBorder(20, 0, 0, 0, new java.awt.Color(255, 63, 52)));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        noOfCus.setFont(new java.awt.Font("Slicker", 1, 60)); // NOI18N
        noOfCus.setForeground(new java.awt.Color(71, 71, 71));
        noOfCus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noOfCus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons used in this project/icons/bgimg noofcus.png"))); // NOI18N
        noOfCus.setText("11");
        jPanel15.add(noOfCus, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 40, 250, 130));

        jPanel13.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 250, 200));

        jPanel16.setBackground(new java.awt.Color(164, 166, 164));
        jPanel16.setBorder(javax.swing.BorderFactory.createMatteBorder(20, 0, 0, 0, new java.awt.Color(255, 63, 52)));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        noOfUsers.setFont(new java.awt.Font("Slicker", 1, 60)); // NOI18N
        noOfUsers.setForeground(new java.awt.Color(71, 71, 71));
        noOfUsers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noOfUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons used in this project/icons/bgimg noofusers.png"))); // NOI18N
        noOfUsers.setText("12");
        jPanel16.add(noOfUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 250, 130));

        jPanel13.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 100, 250, 200));

        jLabel13.setFont(new java.awt.Font("Slicker", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(71, 71, 71));
        jLabel13.setText("No of Users");
        jPanel13.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 60, -1, 30));

        jLabel15.setFont(new java.awt.Font("Slicker", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(71, 71, 71));
        jLabel15.setText("No of Sales");
        jPanel13.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, -1, -1));

        jPanel17.setBackground(new java.awt.Color(164, 166, 164));
        jPanel17.setBorder(javax.swing.BorderFactory.createMatteBorder(20, 0, 0, 0, new java.awt.Color(255, 63, 52)));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        noOfSales.setFont(new java.awt.Font("Slicker", 1, 60)); // NOI18N
        noOfSales.setForeground(new java.awt.Color(71, 71, 71));
        noOfSales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noOfSales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons used in this project/icons/bgimg noofsales.png"))); // NOI18N
        noOfSales.setText("13");
        jPanel17.add(noOfSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 250, 120));

        jPanel13.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 250, 200));

        jPanel19.setBackground(new java.awt.Color(164, 166, 164));
        jPanel19.setBorder(javax.swing.BorderFactory.createMatteBorder(20, 0, 0, 0, new java.awt.Color(255, 63, 52)));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        onGoingRentals.setFont(new java.awt.Font("Slicker", 1, 60)); // NOI18N
        onGoingRentals.setForeground(new java.awt.Color(71, 71, 71));
        onGoingRentals.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        onGoingRentals.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons used in this project/icons/bgimg onGOing rental.png"))); // NOI18N
        onGoingRentals.setText("14");
        jPanel19.add(onGoingRentals, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 250, 120));

        jPanel13.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, 250, 200));

        jLabel19.setFont(new java.awt.Font("Slicker", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(71, 71, 71));
        jLabel19.setText("Ongoing Rental");
        jPanel13.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, -1, -1));

        jLabel21.setFont(new java.awt.Font("Slicker", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(71, 71, 71));
        jLabel21.setText("Pending Payments");
        jPanel13.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 400, -1, -1));

        jPanel20.setBackground(new java.awt.Color(164, 166, 164));
        jPanel20.setBorder(javax.swing.BorderFactory.createMatteBorder(20, 0, 0, 0, new java.awt.Color(255, 63, 52)));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pendingPayments.setFont(new java.awt.Font("Slicker", 1, 60)); // NOI18N
        pendingPayments.setForeground(new java.awt.Color(71, 71, 71));
        pendingPayments.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pendingPayments.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons used in this project/icons/bgimg pending.png"))); // NOI18N
        pendingPayments.setText("15");
        jPanel20.add(pendingPayments, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 250, 120));

        jPanel13.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 440, 250, 200));

        lbluser.setFont(new java.awt.Font("Simplified Arabic", 0, 16)); // NOI18N
        lbluser.setForeground(new java.awt.Color(51, 51, 51));
        lbluser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel13.add(lbluser, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, 230, 20));

        getContentPane().add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 1160, 730));

        setSize(new java.awt.Dimension(1363, 764));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblDressesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDressesMouseClicked
        // TODO add your handling code here:
        
        Dresses Dr = new Dresses();
        Dr.setVisible(true);
        this.hide();
        
    }//GEN-LAST:event_lblDressesMouseClicked

    private void lblRentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRentMouseClicked
        // TODO add your handling code here:
        Rent Re = new Rent();
        Re.setVisible(true);
        this.hide();
        
    }//GEN-LAST:event_lblRentMouseClicked

    private void lblReturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReturnMouseClicked
        // TODO add your handling code here:
        Return Ret = new Return();
        Ret.setVisible(true);
        this.hide();
    }//GEN-LAST:event_lblReturnMouseClicked

    private void lblPaymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPaymentMouseClicked
        // TODO add your handling code here:
        Payment Pay = new Payment();
        Pay.setVisible(true);
        this.hide();
    }//GEN-LAST:event_lblPaymentMouseClicked

    private void lblUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsersMouseClicked
        // TODO add your handling code here:
        Users Us = new Users();
        Us.setVisible(true);
        this.hide();
       
    }//GEN-LAST:event_lblUsersMouseClicked

    private void lblCustomersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCustomersMouseClicked
        // TODO add your handling code here:
        Customers Cus = new Customers();
        Cus.setVisible(true);
        this.hide();
    }//GEN-LAST:event_lblCustomersMouseClicked

    private void lblReportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportsMouseClicked
        // TODO add your handling code here:
        Reports Rep = new Reports();
        Rep.setVisible(true);
        this.hide();
        
    }//GEN-LAST:event_lblReportsMouseClicked

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
       
        Login Log = new Login();
        Log.setVisible(true);
        this.hide();
        
    }//GEN-LAST:event_lblLogoutMouseClicked

    private void lblDressesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDressesMouseEntered
        jPanel6.setBackground(mouseEnteredcolor);
    }//GEN-LAST:event_lblDressesMouseEntered

    private void lblDressesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDressesMouseExited
        jPanel6.setBackground(mouseExitdcolor);
    }//GEN-LAST:event_lblDressesMouseExited

    private void lblRentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRentMouseEntered
        jPanel7.setBackground(mouseEnteredcolor);
    }//GEN-LAST:event_lblRentMouseEntered

    private void lblRentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRentMouseExited
         jPanel7.setBackground(mouseExitdcolor);
    }//GEN-LAST:event_lblRentMouseExited

    private void lblReturnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReturnMouseEntered
       jPanel8.setBackground(mouseEnteredcolor);
    }//GEN-LAST:event_lblReturnMouseEntered

    private void lblReturnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReturnMouseExited
         jPanel8.setBackground(mouseExitdcolor);
    }//GEN-LAST:event_lblReturnMouseExited

    private void lblPaymentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPaymentMouseEntered
        jPanel9.setBackground(mouseEnteredcolor);
    }//GEN-LAST:event_lblPaymentMouseEntered

    private void lblPaymentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPaymentMouseExited
        jPanel9.setBackground(mouseExitdcolor);
    }//GEN-LAST:event_lblPaymentMouseExited

    private void lblUsersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsersMouseEntered
        jPanel10.setBackground(mouseEnteredcolor);
    }//GEN-LAST:event_lblUsersMouseEntered

    private void lblUsersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsersMouseExited
        jPanel10.setBackground(mouseExitdcolor);
    }//GEN-LAST:event_lblUsersMouseExited

    private void lblCustomersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCustomersMouseEntered
         jPanel11.setBackground(mouseEnteredcolor);
    }//GEN-LAST:event_lblCustomersMouseEntered

    private void lblCustomersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCustomersMouseExited
        jPanel11.setBackground(mouseExitdcolor);
    }//GEN-LAST:event_lblCustomersMouseExited

    private void lblReportsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportsMouseEntered
        jPanel12.setBackground(mouseEnteredcolor);
    }//GEN-LAST:event_lblReportsMouseEntered

    private void lblReportsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportsMouseExited
        jPanel12.setBackground(mouseExitdcolor);
    }//GEN-LAST:event_lblReportsMouseExited

    private void lblLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseEntered
        jPanel5.setBackground(LogoutmouseEnteredcolor);
    }//GEN-LAST:event_lblLogoutMouseEntered

    private void lblLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseExited
        jPanel5.setBackground(mouseExitdcolor);
    }//GEN-LAST:event_lblLogoutMouseExited

    private void btnMinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizeActionPerformed
        // Minimize Button
        this.setExtendedState(ManagerMainMenu.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // Close Button
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        
    }//GEN-LAST:event_jPanel6MouseClicked

         /* *********************************************************/
        /* ***************Menu Card Functions************************/ 
        /* *********************************************************/    
    
    public void setDataToCard(){
    
        
        
        long l = System.currentTimeMillis();
        Date todaysDate = new Date(l);
        
        try {
            
            Connection con = DBConnector.getConnection();
            
            Statement st = null;
            ResultSet rs = null;
            
            st = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
            rs = st.executeQuery("select * from dress");
            rs.last();
            noOfItems.setText(Integer.toString(rs.getRow()));
            
            rs = st.executeQuery("select * from customer");
            rs.last();
            noOfCus.setText(Integer.toString(rs.getRow()));
            
            rs = st.executeQuery("select * from user_registration");
            rs.last();
            noOfUsers.setText(Integer.toString(rs.getRow()));
            
            rs = st.executeQuery("select * from payment");
            rs.last();
            noOfSales.setText(Integer.toString(rs.getRow()));
            
            rs = st.executeQuery("select * from rent");
            rs.last();
            onGoingRentals.setText(Integer.toString(rs.getRow()));
            
            rs = st.executeQuery("select * from return_dress");
            rs.last();
            pendingPayments.setText(Integer.toString(rs.getRow()));
            
           
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    
    }
    
    
    
  
    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerMainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnMinimize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblCustomers;
    private javax.swing.JLabel lblDresses;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblPayment;
    private javax.swing.JLabel lblRent;
    private javax.swing.JLabel lblReports;
    private javax.swing.JLabel lblReturn;
    private javax.swing.JLabel lblUsers;
    public javax.swing.JLabel lbluser;
    public javax.swing.JLabel lblwelcome;
    private javax.swing.JLabel noOfCus;
    private javax.swing.JLabel noOfItems;
    private javax.swing.JLabel noOfSales;
    private javax.swing.JLabel noOfUsers;
    private javax.swing.JLabel onGoingRentals;
    private javax.swing.JLabel pendingPayments;
    // End of variables declaration//GEN-END:variables
}
