/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrames;

import Database.DBConnector;
import com.toedter.calendar.JDateChooser;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Selitha Sasmitha
 */
public class Return extends javax.swing.JFrame {

    /**
     * Creates new form Return
     */
    public Return() {
        initComponents();
        
        update_table();     //Calling the Update table function
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblBack = new javax.swing.JLabel();
        btnMinimize = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtDressCode = new app.bolivia.swing.JCTextField();
        jLabel1 = new javax.swing.JLabel();
        txtSize = new app.bolivia.swing.JCTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtStartDate = new app.bolivia.swing.JCTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDueDate = new app.bolivia.swing.JCTextField();
        btnReturn = new rojerusan.RSMaterialButtonRectangle();
        jLabel8 = new javax.swing.JLabel();
        txtDressName = new app.bolivia.swing.JCTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCustName = new app.bolivia.swing.JCTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtCustId = new app.bolivia.swing.JCTextField();
        txtCategory = new app.bolivia.swing.JCTextField();
        txtColor = new app.bolivia.swing.JCTextField();
        txtPrice = new app.bolivia.swing.JCTextField();
        txtTotalDays = new app.bolivia.swing.JCTextField();
        jLabel12 = new javax.swing.JLabel();
        txtOverdueDays = new app.bolivia.swing.JCTextField();
        jLabel13 = new javax.swing.JLabel();
        txtCurrentDate = new app.bolivia.swing.JCTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txttotal = new app.bolivia.swing.JCTextField();
        jLabel17 = new javax.swing.JLabel();
        txtFine = new app.bolivia.swing.JCTextField();
        jPanel2 = new javax.swing.JPanel();
        txtSearch = new app.bolivia.swing.JCTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableReturn = new rojeru_san.complementos.RSTableMetro();
        btnCalculate = new rojerusan.RSMaterialButtonRectangle();
        btnMakePayment1 = new rojerusan.RSMaterialButtonRectangle();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(84, 109, 229));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons used in this project/icons/Back.png"))); // NOI18N
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });
        jPanel1.add(lblBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        btnMinimize.setBackground(new java.awt.Color(84, 109, 229));
        btnMinimize.setForeground(new java.awt.Color(255, 255, 255));
        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons used in this project/icons/Minimize Set 27px.png"))); // NOI18N
        btnMinimize.setAlignmentY(0.0F);
        btnMinimize.setBorder(null);
        btnMinimize.setBorderPainted(false);
        btnMinimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizeActionPerformed(evt);
            }
        });
        jPanel1.add(btnMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 0, 30, 30));

        btnClose.setBackground(new java.awt.Color(84, 109, 229));
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons used in this project/icons/Close Set 27 px.png"))); // NOI18N
        btnClose.setAlignmentY(0.0F);
        btnClose.setBorder(null);
        btnClose.setBorderPainted(false);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 0, 30, 30));

        jLabel15.setFont(new java.awt.Font("Slicker", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Return Dress");
        jLabel15.setToolTipText("");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 150, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 50));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDressCode.setEditable(false);
        txtDressCode.setBackground(new java.awt.Color(51, 51, 51));
        txtDressCode.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtDressCode.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtDressCode.setPhColor(new java.awt.Color(255, 255, 255));
        txtDressCode.setPlaceholder("Dress code ...");
        jPanel3.add(txtDressCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 190, 30));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Dress Code  :");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        txtSize.setEditable(false);
        txtSize.setBackground(new java.awt.Color(51, 51, 51));
        txtSize.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtSize.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtSize.setPhColor(new java.awt.Color(255, 255, 255));
        txtSize.setPlaceholder("Size ...");
        jPanel3.add(txtSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 190, 30));

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Customer ID :");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Catogery :");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 80, -1));

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Size :");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 40, -1));

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Colour :");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        txtStartDate.setEditable(false);
        txtStartDate.setBackground(new java.awt.Color(51, 51, 51));
        txtStartDate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtStartDate.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtStartDate.setPhColor(new java.awt.Color(255, 255, 255));
        txtStartDate.setPlaceholder("Start date ...");
        jPanel3.add(txtStartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 80, 30));

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Price (perday) :");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 100, -1));

        txtDueDate.setEditable(false);
        txtDueDate.setBackground(new java.awt.Color(51, 51, 51));
        txtDueDate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtDueDate.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtDueDate.setPhColor(new java.awt.Color(255, 255, 255));
        txtDueDate.setPlaceholder("Due date ...");
        jPanel3.add(txtDueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 90, 30));

        btnReturn.setText("Return");
        btnReturn.setFont(new java.awt.Font("Slicker", 0, 24)); // NOI18N
        btnReturn.setName(""); // NOI18N
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });
        jPanel3.add(btnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 640, 280, 70));

        jLabel8.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Dress Name  :");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        txtDressName.setEditable(false);
        txtDressName.setBackground(new java.awt.Color(51, 51, 51));
        txtDressName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtDressName.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtDressName.setPhColor(new java.awt.Color(255, 255, 255));
        txtDressName.setPlaceholder("Dress name ...");
        jPanel3.add(txtDressName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 190, 30));

        jLabel9.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Customer Name :");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));

        txtCustName.setEditable(false);
        txtCustName.setBackground(new java.awt.Color(51, 51, 51));
        txtCustName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtCustName.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtCustName.setPhColor(new java.awt.Color(255, 255, 255));
        txtCustName.setPlaceholder("Customer name ...");
        jPanel3.add(txtCustName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 200, 30));

        jLabel10.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Start-Date :");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        jLabel11.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Due-Date :");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 90, -1));

        txtCustId.setBackground(new java.awt.Color(51, 51, 51));
        txtCustId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtCustId.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtCustId.setPhColor(new java.awt.Color(255, 255, 255));
        txtCustId.setPlaceholder("Customer id ...");
        txtCustId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCustIdKeyPressed(evt);
            }
        });
        jPanel3.add(txtCustId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 190, 30));

        txtCategory.setEditable(false);
        txtCategory.setBackground(new java.awt.Color(51, 51, 51));
        txtCategory.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtCategory.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtCategory.setPhColor(new java.awt.Color(255, 255, 255));
        txtCategory.setPlaceholder("Catogery ...");
        jPanel3.add(txtCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 190, 30));

        txtColor.setEditable(false);
        txtColor.setBackground(new java.awt.Color(51, 51, 51));
        txtColor.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtColor.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtColor.setPhColor(new java.awt.Color(255, 255, 255));
        txtColor.setPlaceholder("colour ...");
        jPanel3.add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 190, 30));

        txtPrice.setEditable(false);
        txtPrice.setBackground(new java.awt.Color(51, 51, 51));
        txtPrice.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtPrice.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtPrice.setPhColor(new java.awt.Color(255, 255, 255));
        txtPrice.setPlaceholder("Price ...");
        jPanel3.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 200, 30));

        txtTotalDays.setEditable(false);
        txtTotalDays.setBackground(new java.awt.Color(51, 51, 51));
        txtTotalDays.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtTotalDays.setText("0");
        txtTotalDays.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtTotalDays.setPhColor(new java.awt.Color(255, 255, 255));
        txtTotalDays.setPlaceholder("Total days ...");
        jPanel3.add(txtTotalDays, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 190, 30));

        jLabel12.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Total Days :");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        txtOverdueDays.setEditable(false);
        txtOverdueDays.setBackground(new java.awt.Color(51, 51, 51));
        txtOverdueDays.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtOverdueDays.setText("0");
        txtOverdueDays.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtOverdueDays.setPhColor(new java.awt.Color(255, 255, 255));
        txtOverdueDays.setPlaceholder("Overdue days ...");
        jPanel3.add(txtOverdueDays, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 200, 30));

        jLabel13.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Overdue Days :");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, -1, -1));

        txtCurrentDate.setEditable(false);
        txtCurrentDate.setBackground(new java.awt.Color(51, 51, 51));
        txtCurrentDate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtCurrentDate.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtCurrentDate.setPhColor(new java.awt.Color(255, 255, 255));
        txtCurrentDate.setPlaceholder("Current days ...");
        jPanel3.add(txtCurrentDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 200, 30));

        jLabel14.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Current Day :");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 90, -1));

        jLabel16.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Total :");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        txttotal.setEditable(false);
        txttotal.setBackground(new java.awt.Color(51, 51, 51));
        txttotal.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txttotal.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txttotal.setPhColor(new java.awt.Color(255, 255, 255));
        txttotal.setPlaceholder("Total price ..");
        jPanel3.add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 200, 30));

        jLabel17.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Fine :");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, -1, -1));

        txtFine.setEditable(false);
        txtFine.setBackground(new java.awt.Color(51, 51, 51));
        txtFine.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtFine.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtFine.setPhColor(new java.awt.Color(255, 255, 255));
        txtFine.setPlaceholder("Fine ...");
        jPanel3.add(txtFine, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 200, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 490, 730));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSearch.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 2, true));
        txtSearch.setPlaceholder("Enter rent item ...");
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        jPanel2.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 830, -1));

        jtableReturn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer ID", "Name", "Dress Code", "Dress Name", "Category", "Size", "Color", "Price (perday)", "Start Date", "Due Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtableReturn.setFuenteFilas(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtableReturn.setFuenteFilasSelect(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtableReturn.setFuenteHead(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jtableReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableReturnMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtableReturn);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 830, 450));

        btnCalculate.setBackground(new java.awt.Color(51, 51, 51));
        btnCalculate.setText("Calculate");
        btnCalculate.setFont(new java.awt.Font("Slicker", 0, 24)); // NOI18N
        btnCalculate.setName(""); // NOI18N
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });
        jPanel2.add(btnCalculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, 220, -1));

        btnMakePayment1.setBackground(new java.awt.Color(51, 51, 51));
        btnMakePayment1.setText("Make Payment");
        btnMakePayment1.setFont(new java.awt.Font("Slicker", 0, 24)); // NOI18N
        btnMakePayment1.setName(""); // NOI18N
        btnMakePayment1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMakePayment1MouseClicked(evt);
            }
        });
        btnMakePayment1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakePayment1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnMakePayment1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 610, 220, -1));

        jLabel7.setFont(new java.awt.Font("Slicker", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("On Going Rentals");
        jLabel7.setToolTipText("");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 250, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 880, 730));

        setSize(new java.awt.Dimension(1363, 764));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        
        
        //Calculate the Dates and prices fucntion
        
        String Dcode = txtDressCode.getText();
        String C_ID = txtCustId.getText();
                
        SimpleDateFormat Date_Format1 = new SimpleDateFormat("yyyy-MM-dd");
        Date date = new Date();
        txtCurrentDate.setText(Date_Format1.format(date));
        
                
        if(C_ID.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Select A Dress to Calculate");
        }
        
              
        else
         {
           
            try {
            DBConnector dbCon = new DBConnector();
            Connection con = dbCon.getConnection();
             
                       
            PreparedStatement pst1 = null;
            pst1 = con.prepareStatement("SELECT `dressCode`,DATEDIFF(end_date,st_date) as `RentDays`, DATEDIFF(NOW(),`end_date`) as `TotDays` FROM `rent` WHERE `custId`=? AND `dressCode`=? ");
            pst1.setString(1, C_ID);
            pst1.setString(2, Dcode);
            ResultSet rs2 ;
            rs2 = pst1.executeQuery();
            
            if(rs2.next() == false)
            {
                JOptionPane.showMessageDialog(this, "Dress Not Found");
            }
            else
            {
                String Rent_Days = rs2.getString("RentDays");
                int no_of_RentDays = Integer.parseInt(Rent_Days);
                
                String Tot_Days = rs2.getString("TotDays");         //Overdue dates
                int no_of_TotDays = Integer.parseInt(Tot_Days);
                
                txtTotalDays.setText(Rent_Days);
                
                int Price_perday = Integer.parseInt(txtPrice.getText());          
                int total = Integer.parseInt(txtPrice.getText()) * no_of_RentDays;
                
                
                txttotal.setText(String.valueOf(total));
                
                    if (no_of_TotDays > 0)
                    {
                      txtOverdueDays.setText(Tot_Days);
                      
                      int fine = (Price_perday + (Price_perday / 2)) * no_of_TotDays;
                      txtFine.setText(String.valueOf(fine));
                    }
                    
                    else
                    {
                      txtOverdueDays.setText("0");
                      txtFine.setText(String.valueOf(0));
                    }
                   
                
            }
             
         }
         catch (SQLException ex) {
            Logger.getLogger(Return.class.getName()).log(Level.SEVERE, null, ex);
        }
            
       }
        
        
        
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
       ManagerMainMenu menu = new ManagerMainMenu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblBackMouseClicked

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
       
        //Search text field codes
        
        DefaultTableModel d1 = (DefaultTableModel)jtableReturn.getModel();
        String search = txtSearch.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(d1);
        jtableReturn.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_txtSearchKeyReleased

    private void jtableReturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableReturnMouseClicked
        
        //update text fields upon mouse click 
        
        DefaultTableModel d2 = (DefaultTableModel)jtableReturn.getModel();
        int selectIndex = jtableReturn.getSelectedRow();
        
        txtCustId.setText(d2.getValueAt(selectIndex, 0).toString());
        txtCustName.setText(d2.getValueAt(selectIndex, 1).toString());
        txtDressCode.setText(d2.getValueAt(selectIndex, 2).toString());
        txtDressName.setText(d2.getValueAt(selectIndex, 3).toString());
        txtCategory.setText(d2.getValueAt(selectIndex, 4).toString());
        txtSize.setText(d2.getValueAt(selectIndex, 5).toString());
        txtColor.setText(d2.getValueAt(selectIndex, 6).toString());
        txtPrice.setText(d2.getValueAt(selectIndex, 7).toString());
        txtStartDate.setText(d2.getValueAt(selectIndex, 8).toString());
        txtDueDate.setText(d2.getValueAt(selectIndex, 9).toString());
        
        txtTotalDays.setText("");
        txtOverdueDays.setText("");
        txtCurrentDate.setText("");
        txtFine.setText("");
        txttotal.setText("");
        
        
    }//GEN-LAST:event_jtableReturnMouseClicked

    private void btnMakePayment1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakePayment1ActionPerformed
        
        Payment Pay = new Payment();
        Pay.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnMakePayment1ActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        
        //return button codes
        
        String custid = txtCustId.getText();
        String custname = txtCustName.getText();
        String dresscode = txtDressCode.getText();
        String dressname = txtDressName.getText();
        String dresscategory = txtCategory.getText();
        String dresssize = txtSize.getText();
        String dresscolor = txtColor.getText();
        Integer dressprice = Integer.parseInt(txtPrice.getText());
        String stdate = txtStartDate.getText();
        String duedate = txtDueDate.getText();
        Integer totaldays = Integer.parseInt(txtTotalDays.getText());
        Integer overduedays = Integer.parseInt(txtOverdueDays.getText());
        String currentday = txtCurrentDate.getText();
        double fine = Double.parseDouble(txtFine.getText());
        double totalprice = Double.parseDouble(txttotal.getText());
 
        /* *********************************************************/
        /* ********* Validation for the  fields ***************/ 
        /* *********************************************************/ 
        
        if(custid.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Insert A Customer ID");
        }
                      
        else if(dresscode.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Insert a Dress Code");
        }
        else if(currentday.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Click Calculate before return");
        }
        
        else if(totaldays.equals(0))
        {
            JOptionPane.showMessageDialog(null,"Click Calculate before return");
        }
       
        else {
  
        try {
            DBConnector dbCon = new DBConnector();
            Connection con = dbCon.getConnection();
           
            PreparedStatement pst = null;
            pst = con.prepareStatement("INSERT INTO `return_dress`(`c_id`, `c_name`, `d_code`,`d_name`, `d_category`, "
                    + "`d_size`, `d_color`, `d_price`, `st_date`, `due_date`, `tot_days`, `overdue_days`,"
                    + " `current_date`, `fine`, `total`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
            
            pst.setString(1, custid);
            pst.setString(2, custname);
            pst.setString(3, dresscode);
            pst.setString(4, dressname);
            pst.setString(5, dresscategory);
            pst.setString(6, dresssize); 
            pst.setString(7, dresscolor); 
            pst.setInt(8, dressprice); 
            pst.setString(9, stdate);
            pst.setString(10, duedate);
            pst.setInt(11, totaldays);
            pst.setInt(12, overduedays);
            pst.setString(13, currentday);
            pst.setDouble(14, fine);
            pst.setDouble(15, totalprice);
            pst.executeUpdate();
   
                       
            PreparedStatement pst2 = null;
            pst2 = con.prepareStatement("UPDATE `dress` SET `quantity`= (quantity + 1) WHERE `dress_code`=?");
            
            pst2.setString(1, dresscode);
            pst2.executeUpdate();
            
            PreparedStatement pst3 = null;
            pst3 = con.prepareStatement("DELETE FROM `rent` WHERE `custId`=? AND `dressCode`=? ");
            pst3.setString(1, custid);
            pst3.setString(2, dresscode);
            pst3.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Dress Returned Successfully");
            
            update_table();
      
            txtCustId.setText("");
            txtCustName.setText("");
            txtDressCode.setText("");
            txtDressName.setText("");
            txtCategory.setText("");
            txtSize.setText("");
            txtColor.setText("");
            txtPrice.setText("");
            txtStartDate.setText("");
            txtDueDate.setText("");
            txtTotalDays.setText("");
            txtOverdueDays.setText("");
            txtCurrentDate.setText("");
            txtFine.setText("");
            txttotal.setText("");
            
                              
            
        }       
            catch (SQLException ex) {
            Logger.getLogger(Return.class.getName()).log(Level.SEVERE, null, ex);
            
        }
        }
   
        
        
    }//GEN-LAST:event_btnReturnActionPerformed


         /* *********************************************************/
        /**** show customer details for the given customer ID **********/ 
        /* *********************************************************/ 
    
    private void txtCustIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustIdKeyPressed
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            String cusid = txtCustId.getText();

            try {
                DBConnector dbCon = new DBConnector();
                Connection con = dbCon.getConnection();

                PreparedStatement pst1 = null;
                pst1 = con.prepareStatement("SELECT * FROM `rent` WHERE `custId`=?");
                pst1.setString(1, cusid);
                ResultSet rs = pst1.executeQuery();

                if(rs.next()==false)
                {
                    JOptionPane.showMessageDialog(this, "No Records Found for NIC Number");
                }
                else
                {
                    String cusname = rs.getString("custName");
                    txtCustName.setText(cusname.trim());
                    String dresscode  = rs.getString("dressCode");
                    txtDressCode.setText(dresscode.trim());
                    String dressname  = rs.getString("dressName");
                    txtDressName.setText(dressname.trim());
                    String dresscategory  = rs.getString("category");
                    txtCategory.setText(dresscategory.trim());
                    String  dresssize = rs.getString("size");
                    txtSize.setText(dresssize.trim());
                    String dresscolor  = rs.getString("color");
                    txtColor.setText(dresscolor.trim());
                    String  dressprice = rs.getString("price");
                    txtPrice.setText(dressprice.trim());
                    String  stdate = rs.getString("st_date");
                    txtStartDate.setText(stdate.trim());
                    String duedate  = rs.getString("end_date");
                    txtDueDate.setText(duedate.trim());
                                       
                }

            }
            catch (SQLException ex) {
                Logger.getLogger(Rent.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_txtCustIdKeyPressed

    private void btnMinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizeActionPerformed
        // Minimize Button
        this.setExtendedState(ManagerMainMenu.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // Close Button
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnMakePayment1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMakePayment1MouseClicked
       Payment Pay = new Payment();
        Pay.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnMakePayment1MouseClicked

    
    
    
    
     public void update_table()
    {
        int c;
        
         try {
            DBConnector dbCon = new DBConnector();
            Connection con = dbCon.getConnection();
           
            PreparedStatement pst = null;
            pst = con.prepareStatement("SELECT * FROM `rent`");
            ResultSet Rs  = pst.executeQuery();
            
            ResultSetMetaData rd = Rs.getMetaData();
            c = rd.getColumnCount();
            DefaultTableModel df = (DefaultTableModel)jtableReturn.getModel();
            df.setRowCount(0);
            
            while(Rs.next())
            {
                Vector v2 = new Vector();
                for (int i=1; i<=c; i++)
                {
                   v2.add(Rs.getString("custId"));
                   v2.add(Rs.getString("custName"));
                   v2.add(Rs.getString("dressCode"));
                   v2.add(Rs.getString("dressName"));
                   v2.add(Rs.getString("category"));
                   v2.add(Rs.getString("size"));
                   v2.add(Rs.getString("color"));
                   v2.add(Rs.getInt("price"));
                   v2.add(Rs.getDate("st_date"));
                   v2.add(Rs.getDate("end_date"));
                }
                
                df.addRow(v2);
                
            }
          
            
        } catch (SQLException ex) {
            Logger.getLogger(Return.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
     
     
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Return().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle btnCalculate;
    private javax.swing.JButton btnClose;
    private rojerusan.RSMaterialButtonRectangle btnMakePayment1;
    private javax.swing.JButton btnMinimize;
    private rojerusan.RSMaterialButtonRectangle btnReturn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private rojeru_san.complementos.RSTableMetro jtableReturn;
    private javax.swing.JLabel lblBack;
    private app.bolivia.swing.JCTextField txtCategory;
    private app.bolivia.swing.JCTextField txtColor;
    private app.bolivia.swing.JCTextField txtCurrentDate;
    private app.bolivia.swing.JCTextField txtCustId;
    private app.bolivia.swing.JCTextField txtCustName;
    private app.bolivia.swing.JCTextField txtDressCode;
    private app.bolivia.swing.JCTextField txtDressName;
    private app.bolivia.swing.JCTextField txtDueDate;
    private app.bolivia.swing.JCTextField txtFine;
    private app.bolivia.swing.JCTextField txtOverdueDays;
    private app.bolivia.swing.JCTextField txtPrice;
    private app.bolivia.swing.JCTextField txtSearch;
    private app.bolivia.swing.JCTextField txtSize;
    private app.bolivia.swing.JCTextField txtStartDate;
    private app.bolivia.swing.JCTextField txtTotalDays;
    private app.bolivia.swing.JCTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
