/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrames;

import Database.DBConnector;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Selitha Sasmitha
 */
public class Users extends javax.swing.JFrame {

    /**
     * Creates new form Users
     */
    public Users() {
        initComponents();
        update_table_user();    //Calling the Update table function
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        btnMinimize = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn_addUser = new rojerusan.RSMaterialButtonRectangle();
        cmbrole = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtemail = new app.bolivia.swing.JCTextField();
        jLabel11 = new javax.swing.JLabel();
        txtnic = new app.bolivia.swing.JCTextField();
        jLabel13 = new javax.swing.JLabel();
        txtphone = new app.bolivia.swing.JCTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaddress = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        txtfname = new app.bolivia.swing.JCTextField();
        txtlname = new app.bolivia.swing.JCTextField();
        txtrepass = new rojerusan.RSPasswordTextPlaceHolder();
        txtpass = new rojerusan.RSPasswordTextPlaceHolder();
        jPanel2 = new javax.swing.JPanel();
        txtsearchuser = new app.bolivia.swing.JCTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableusers = new rojeru_san.complementos.RSTableMetro();
        btnDeleteUser = new rojerusan.RSMaterialButtonRectangle();
        btnUpdateUser = new rojerusan.RSMaterialButtonRectangle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(84, 109, 229));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons used in this project/icons/Back.png"))); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        btnMinimize.setBackground(new java.awt.Color(84, 109, 229));
        btnMinimize.setForeground(new java.awt.Color(255, 255, 255));
        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons used in this project/icons/Minimize Set 27px.png"))); // NOI18N
        btnMinimize.setAlignmentY(0.0F);
        btnMinimize.setBorder(null);
        btnMinimize.setBorderPainted(false);
        btnMinimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizeActionPerformed(evt);
            }
        });
        jPanel1.add(btnMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 0, 30, 30));

        btnClose.setBackground(new java.awt.Color(84, 109, 229));
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons used in this project/icons/Close Set 27 px.png"))); // NOI18N
        btnClose.setAlignmentY(0.0F);
        btnClose.setBorder(null);
        btnClose.setBorderPainted(false);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 0, 30, 30));

        jLabel6.setFont(new java.awt.Font("Slicker", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("User Registration");
        jLabel6.setToolTipText("");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 210, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 50));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_addUser.setText("ADD");
        btn_addUser.setFont(new java.awt.Font("Slicker", 0, 24)); // NOI18N
        btn_addUser.setName(""); // NOI18N
        btn_addUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addUserActionPerformed(evt);
            }
        });
        jPanel3.add(btn_addUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 630, 280, 70));

        cmbrole.setBackground(new java.awt.Color(51, 51, 51));
        cmbrole.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbrole.setForeground(new java.awt.Color(255, 255, 255));
        cmbrole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manager", "Operator" }));
        cmbrole.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel3.add(cmbrole, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 230, 30));

        jLabel8.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons used in this project/icons/Role (40 × 40 px).png"))); // NOI18N
        jLabel8.setText("Role :");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 90, -1));

        jLabel9.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons used in this project/icons/Email (40 × 40 px).png"))); // NOI18N
        jLabel9.setText("Email :");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 90, -1));

        txtemail.setBackground(new java.awt.Color(51, 51, 51));
        txtemail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtemail.setPhColor(new java.awt.Color(255, 255, 255));
        txtemail.setPlaceholder("Enter your email");
        jPanel3.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 220, 30));

        jLabel11.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons used in this project/icons/NIC (40 × 40 px).png"))); // NOI18N
        jLabel11.setText("NIC :");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));

        txtnic.setBackground(new java.awt.Color(51, 51, 51));
        txtnic.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtnic.setPhColor(new java.awt.Color(255, 255, 255));
        txtnic.setPlaceholder("Enter your NIC number");
        jPanel3.add(txtnic, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 220, 30));

        jLabel13.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons used in this project/icons/Phone (40 × 40 px).png"))); // NOI18N
        jLabel13.setText("Phone :");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, -1, -1));

        txtphone.setBackground(new java.awt.Color(51, 51, 51));
        txtphone.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtphone.setPhColor(new java.awt.Color(255, 255, 255));
        txtphone.setPlaceholder("Enter your phone number");
        txtphone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtphoneKeyTyped(evt);
            }
        });
        jPanel3.add(txtphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 220, 30));

        jLabel16.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons used in this project/icons/Address(40 × 40 px).png"))); // NOI18N
        jLabel16.setText("Address :");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, -1, -1));

        jLabel19.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons used in this project/icons/Password (40 × 40 px).png"))); // NOI18N
        jLabel19.setText("Password :");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, -1, -1));

        jLabel20.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons used in this project/icons/Re-Password (40 × 40 px).png"))); // NOI18N
        jLabel20.setText("Re-enter Password :");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, -1, -1));

        txtaddress.setBackground(new java.awt.Color(51, 51, 51));
        txtaddress.setColumns(20);
        txtaddress.setRows(5);
        txtaddress.setBorder(null);
        jScrollPane2.setViewportView(txtaddress);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 220, 70));

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons used in this project/icons/User (40 × 40 px).png"))); // NOI18N
        jLabel5.setText("User Name:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 120, 30));

        txtfname.setBackground(new java.awt.Color(51, 51, 51));
        txtfname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtfname.setPhColor(new java.awt.Color(255, 255, 255));
        txtfname.setPlaceholder("First name");
        jPanel3.add(txtfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 110, 30));

        txtlname.setBackground(new java.awt.Color(51, 51, 51));
        txtlname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtlname.setPhColor(new java.awt.Color(255, 255, 255));
        txtlname.setPlaceholder("Last name");
        jPanel3.add(txtlname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 105, 30));

        txtrepass.setBackground(new java.awt.Color(51, 51, 51));
        txtrepass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtrepass.setPhColor(new java.awt.Color(255, 255, 255));
        txtrepass.setPlaceholder("Confirm your password");
        jPanel3.add(txtrepass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 580, 210, -1));

        txtpass.setBackground(new java.awt.Color(51, 51, 51));
        txtpass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtpass.setPhColor(new java.awt.Color(255, 255, 255));
        txtpass.setPlaceholder("Enter your password");
        jPanel3.add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 210, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 300, 730));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtsearchuser.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 2, true));
        txtsearchuser.setPlaceholder("Enter user name ...");
        txtsearchuser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchuserKeyReleased(evt);
            }
        });
        jPanel2.add(txtsearchuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1030, -1));

        jtableusers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Role", "Email", "NIC", "Phone", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtableusers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableusersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtableusers);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 1030, 460));

        btnDeleteUser.setBackground(new java.awt.Color(51, 51, 51));
        btnDeleteUser.setText("Delete");
        btnDeleteUser.setFont(new java.awt.Font("Slicker", 0, 24)); // NOI18N
        btnDeleteUser.setName(""); // NOI18N
        btnDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteUserActionPerformed(evt);
            }
        });
        jPanel2.add(btnDeleteUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 570, 190, -1));

        btnUpdateUser.setBackground(new java.awt.Color(51, 51, 51));
        btnUpdateUser.setText("Update");
        btnUpdateUser.setFont(new java.awt.Font("Slicker", 0, 24)); // NOI18N
        btnUpdateUser.setName(""); // NOI18N
        btnUpdateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateUserActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdateUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 190, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 1070, 730));

        setSize(new java.awt.Dimension(1363, 764));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteUserActionPerformed
        
        //Delete user button codes
        
        DefaultTableModel d1 = (DefaultTableModel)jtableusers.getModel();

        int selectIndex = jtableusers.getSelectedRow();

        String nic = d1.getValueAt(selectIndex,4).toString();

        int  dialogResult = JOptionPane.showConfirmDialog(this,"Aye you Sure to Delete The User?","Warning",JOptionPane.YES_NO_OPTION);

        if(dialogResult == JOptionPane.YES_OPTION)
        {
            try {

                DBConnector dbCon = new DBConnector();
                Connection con = dbCon.getConnection();

                PreparedStatement pst = null;
                pst = con.prepareStatement("DELETE FROM `user_registration` WHERE `nic`=?");

                pst.setString(1,nic);
                pst.executeUpdate();

                JOptionPane.showMessageDialog(this, "User Record Deleted");
                update_table_user();
            
            /* *************************/
            /* Clearing the text fields*/ 
            /* *************************/
                
            txtfname.setText("");
            txtlname.setText("");
            cmbrole.setSelectedIndex(-1);
            txtemail.setText("");
            txtnic.setText("");
            txtphone.setText("");
            txtaddress.setText("");
            txtpass.setText("");
            txtrepass.setText("");
            txtfname.requestFocus();
                

            } catch (SQLException ex) {
                Logger.getLogger(Users.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btnDeleteUserActionPerformed

    private void btnUpdateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateUserActionPerformed
           
            String fname = txtfname.getText();
            String lname = txtlname.getText();
            String role = cmbrole.getSelectedItem().toString();
            String email = txtemail.getText();
            String nic = txtnic.getText();
            String phone = txtphone.getText();
            String address = txtaddress.getText();
            String pass = String.valueOf(txtpass.getPassword());
            String repass = String.valueOf(txtrepass.getPassword());
           
            Pattern p = Pattern.compile("^[0][0-9]{9}$");
            Matcher m = p.matcher(txtphone.getText());
        
            String expression2 = "[A-Za-z0-9]+@+[A-Za-z]+\\.+[A-Za-z]{2,4}+$";
            Pattern p3 = Pattern.compile(expression2);
            Matcher m3 = p3.matcher(txtemail.getText());  // Email validation
     
            
         /* *********************************************************/
        /************* Validation for th fields *********************/ 
        /* *********************************************************/ 
            
        if(fname.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Insert first name");
        }
        
        else if(lname.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Insert last name");
        }
        
        else if(!m3.matches())
        {
            JOptionPane.showMessageDialog(null, "Invalid email address");
        }
        
        else if(nic.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Insert NIC number");
        }
        
        else if(!m.matches())
        {
            JOptionPane.showMessageDialog(null, "Invalid Phone Number!");
        }
        
        else if(address.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Insert permanent address");
        }
        
        else if(pass.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Insert password");
        }
        
        else if(!pass.equals(repass)) //check the repeat password matches
        {
            JOptionPane.showMessageDialog(null, "Password Does Not Match");
        }
                
        else
        {
        
            try {
               

            DBConnector dbCon = new DBConnector();
            Connection con = dbCon.getConnection();

            PreparedStatement pst = null;
            pst = con.prepareStatement("UPDATE `user_registration` SET `firstName`=?,"
                    + "`lastName`=?,`role`=?,`email`=?,`phone`=?,`address`=?,`password`=? WHERE `nic`=?");

            pst.setString(1,fname);
            pst.setString(2,lname);
            pst.setString(3,role);
            pst.setString(4,email);
            pst.setString(5,phone);
            pst.setString(6,address);
            pst.setString(7,pass);
            pst.setString(8,nic);
            
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "User Details Updated");
            update_table_user();
            
            txtfname.setText("");
            txtlname.setText("");
            cmbrole.setSelectedIndex(-1);
            txtemail.setText("");
            txtnic.setText("");
            txtphone.setText("");
            txtaddress.setText("");
            txtpass.setText("");
            txtrepass.setText("");
            txtfname.requestFocus();

        } catch (SQLException ex) {
            Logger.getLogger(Users.class.getName()).log(Level.SEVERE, null, ex);
        } 
        }
         
    }//GEN-LAST:event_btnUpdateUserActionPerformed

    private void btn_addUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addUserActionPerformed
        // Add user button codes
        
        String fname = txtfname.getText();
        String lname = txtlname.getText();
        String role = cmbrole.getSelectedItem().toString();
        String email = txtemail.getText();
        String nic = txtnic.getText();
        String phone = txtphone.getText();
        String address = txtaddress.getText();
        String pass = String.valueOf(txtpass.getPassword());
        String repass = String.valueOf(txtrepass.getPassword());
        
        Pattern p = Pattern.compile("^[0][0-9]{9}$");
        Matcher m = p.matcher(txtphone.getText());
        
        String expression2 = "[A-Za-z0-9]+@+[A-Za-z]+\\.+[A-Za-z]{2,4}+$";
        Pattern p3 = Pattern.compile(expression2);
        Matcher m3 = p3.matcher(txtemail.getText());  // Email validation
        
         /* *********************************************************/
        /************* Validation for th fields *********************/ 
        /* *********************************************************/
        
        if(fname.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Insert first name");
        }
        
        else if(lname.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Insert last name");
        }
        
        else if(!m3.matches())
        {
            JOptionPane.showMessageDialog(null, "Invalid email address");
        }
        
        else if(nic.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Insert NIC number");
        }
        
        else if(!m.matches())
        {
            JOptionPane.showMessageDialog(null, "Invalid Phone Number!");
        }
        
        else if(address.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Insert permanent address");
        }
        
        else if(pass.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Insert password");
        }
        
        else if(!pass.equals(repass)) //check the repeat password matches
        {
            JOptionPane.showMessageDialog(null, "Password Does Not Match");
        }
        else if(checkEmail(email))
        {
            JOptionPane.showMessageDialog(null,"Email Already Exist"); // check exiasting emails
        }
        
        else
        {
            PreparedStatement st;
            String query = "INSERT INTO `user_registration`(`firstName`, `lastName`,"
                    + "`role`, `email`, `nic`, `phone`, `address`, `password`) VALUES (?,?,?,?,?,?,?,?)";
      
        try {
            st = DBConnector.getConnection().prepareStatement(query);
            
            st.setString(1, fname);
            st.setString(2, lname);
            st.setString(3, role);
            st.setString(4, email);
            st.setString(5, nic);
            st.setString(6, phone);
            st.setString(7, address);
            st.setString(8, pass);
            
            if(st.executeUpdate() > 0)
            {
                JOptionPane.showMessageDialog(null,"New User Added");
            }
            
            update_table_user();
            
            txtfname.setText("");
            txtlname.setText("");
            cmbrole.setSelectedIndex(-1);
            txtemail.setText("");
            txtnic.setText("");
            txtphone.setText("");
            txtaddress.setText("");
            txtpass.setText("");
            txtrepass.setText("");
            txtfname.requestFocus();
            
        } catch (SQLException ex) {
            Logger.getLogger(Users.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        }
        
    }//GEN-LAST:event_btn_addUserActionPerformed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        ManagerMainMenu menu = new ManagerMainMenu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel15MouseClicked

    private void txtphoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtphoneKeyTyped
      //function to enter only numbers to the phone no text field  
        char c = evt.getKeyChar();
       if(!Character.isDigit(c))
        {
            evt.consume();
           // JOptionPane.showMessageDialog(null, "Insert a Quantity");
        }
    }//GEN-LAST:event_txtphoneKeyTyped

    private void jtableusersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableusersMouseClicked
        //Update text fields on the table mouse clicked
        
         DefaultTableModel d1 = (DefaultTableModel)jtableusers.getModel();

        int selectIndex = jtableusers.getSelectedRow();

        txtfname.setText(d1.getValueAt(selectIndex, 0).toString());
        txtlname.setText(d1.getValueAt(selectIndex, 1).toString());
        cmbrole.setSelectedItem(d1.getValueAt(selectIndex, 2).toString());
        txtemail.setText(d1.getValueAt(selectIndex, 3).toString());
        txtnic.setText(d1.getValueAt(selectIndex, 4).toString());
        txtphone.setText(d1.getValueAt(selectIndex, 5).toString());
        txtaddress.setText(d1.getValueAt(selectIndex, 6).toString());
        
        
        
    }//GEN-LAST:event_jtableusersMouseClicked

    private void txtsearchuserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchuserKeyReleased
        //search text field key typed result
        
        DefaultTableModel d1 = (DefaultTableModel)jtableusers.getModel();
        String search = txtsearchuser.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(d1);
        jtableusers.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_txtsearchuserKeyReleased

    private void btnMinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizeActionPerformed
        // Minimize Button
        this.setExtendedState(ManagerMainMenu.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // Close Button
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

        /* *********************************************************/
        /*     Function to Check the email already exists          */ 
        /* *********************************************************/
    
    public boolean checkEmail(String mail)
    {
       PreparedStatement st;
       ResultSet rs;
       boolean checkUser = false;
       String query = "SELECT * FROM `user_registration` WHERE `email` =?";
       
        try 
        {
            st = DBConnector.getConnection().prepareStatement(query);
            st.setString(1,mail);
            
            rs = st.executeQuery();
            
            if(rs.next())
            {
                checkUser = true;
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Users.class.getName()).log(Level.SEVERE, null, ex);
        }
      
        return checkUser;
       
    }
    
        /* *********************************************************/
        /*                update table function                    */ 
        /* *********************************************************/
    
    public void update_table_user()
    {
        int T;
        
         try {
            DBConnector dbCon = new DBConnector();
            Connection con = dbCon.getConnection();
           
            PreparedStatement pst = null;
            pst = con.prepareStatement("SELECT * FROM `user_registration`");
            ResultSet Rs  = pst.executeQuery();
            
            ResultSetMetaData rd = Rs.getMetaData();
            T = rd.getColumnCount();
            DefaultTableModel df = (DefaultTableModel)jtableusers.getModel();
            df.setRowCount(0);
            
            while(Rs.next())
            {
                Vector v2 = new Vector();
                for (int i=1; i<=T; i++)
                {
                   v2.add(Rs.getString("firstName"));
                   v2.add(Rs.getString("lastName"));
                   v2.add(Rs.getString("role"));
                   v2.add(Rs.getString("email"));
                   v2.add(Rs.getString("nic"));
                   v2.add(Rs.getString("phone"));
                   v2.add(Rs.getString("address"));
                   v2.add(Rs.getString("password"));
                   
                }
                
                df.addRow(v2);
                
            }
          
            
        } catch (SQLException ex) {
            Logger.getLogger(Customers.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Users().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private rojerusan.RSMaterialButtonRectangle btnDeleteUser;
    private javax.swing.JButton btnMinimize;
    private rojerusan.RSMaterialButtonRectangle btnUpdateUser;
    private rojerusan.RSMaterialButtonRectangle btn_addUser;
    private javax.swing.JComboBox<String> cmbrole;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private rojeru_san.complementos.RSTableMetro jtableusers;
    private javax.swing.JTextArea txtaddress;
    private app.bolivia.swing.JCTextField txtemail;
    private app.bolivia.swing.JCTextField txtfname;
    private app.bolivia.swing.JCTextField txtlname;
    private app.bolivia.swing.JCTextField txtnic;
    private rojerusan.RSPasswordTextPlaceHolder txtpass;
    private app.bolivia.swing.JCTextField txtphone;
    private rojerusan.RSPasswordTextPlaceHolder txtrepass;
    private app.bolivia.swing.JCTextField txtsearchuser;
    // End of variables declaration//GEN-END:variables
}
